---
title: "Preliminary List of Candidate Species"
author: Pratik Gupte
date: May, 2021
output: 
  pdf_document: 
    latex_engine: xelatex
mainfont: Source Serif Pro
editor_options:
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE}
library(data.table)

# load species and print by flyway
data = list.files("data/output/", pattern = "candidate_species",
                  full.names = T)
data = lapply(data, fread)
```

```{r, echo=FALSE}
knitr::kable(data[[1]][, c("Scientific name", "Common name",
                           "Total observations (2015-2019)")],
             caption = "Candidate species that primarily migrate along\\ 
             the Central Asian Flyway.")
```

```{r, echo=FALSE}
knitr::kable(data[[2]][, c("Scientific name", "Common name",
                           "Total observations (2015-2019)")],
             caption = "Candidate species that primarily migrate along\\ 
             the potential Indo-European Flyway.")

```

```{r, echo=FALSE}
knitr::kable(data[[3]][, c("Scientific name", "Common name",
                           "Total observations (2015-2019)")],
             caption = "Candidate species that primarily migrate within the Indian subcontinent.")

```
